increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
burn(p,n) :- msgSender(s),balanceOf(p,balanceOf_x1),o==s,balanceOf_x1>0,owner(o),recv_burn(p,n).
freeze(p,n) :- recv_freeze(p,n),balanceOf(p,balanceOf_x1),0!=balanceOf_x1.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(r,balanceOf_x1),0!=balanceOf_x1.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),balanceOf(o,balanceOf_x1),balanceOf_x1>0.
withdrawEther(p,n) :- recv_withdrawEther(p,n).
unfreeze(p,n) :- recv_unfreeze(p,n),n>=0.