Interfaces:
allowance(address,address): int
recv_transferFrom(address,address,address,int)
recv_mint(address,int)
recv_increaseAllowance(address,address,int)
recv_withdrawEther(address,int)
recv_transfer(address,address,int)
recv_freeze(address,int)
totalSupply(): int
recv_burn(address,int)
recv_unfreeze(address,int)
balanceOf(address): int
Indices:
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalUnfreeze,List(address, int),List(p, n)) -> List(0)
SimpleRelation(freezeOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(totalFreeze,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeAllowance,List(address, address, int),List(s, p, n)) -> List(0, 1)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
Rules:
freezeOf(p,n) :- totalFreeze(p,f),totalUnfreeze(p,u),n := f-u.
balanceOf(p,s) :- s := (((n+i)-m)-o)-f,totalBurn(p,m),freezeOf(p,f),totalMint(p,n),totalOut(p,o),totalIn(p,i).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
unequalBalance(s,n) :- totalBalances(s),freezeSum(f),totalSupply(n),s+f>n.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
invalidTx() :- recv_burn(_,_),owner(o),msgSender(s),o!=s.
transferFrom(o,r,s,n) :- n>0,allowance(o,s,allowance_x2_1),n<allowance_x2_1,balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<balanceOf_x1_2.
allowanceTotal(o,s,m) :- increaseAllowance(o,s,_),m = sum n: increaseAllowance(o,s,n).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
allMint(s) :- s = sum n: mint(_,n).
freeze(p,n) :- recv_freeze(p,n),balanceOf(p,balanceOf_x1),n<balanceOf_x1.
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
totalUnfreeze(p,s) :- unfreeze(p,_),s = sum n: unfreeze(p,n).
owner(s) :- constructor(_),msgSender(s).
negativeAllowance(s,p,n) :- allowance(s,p,n),n<0,s!=address(0),p!=address(0).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
withdrawEther(p,n) :- recv_withdrawEther(p,n).
totalFreeze(p,s) :- freeze(p,_),s = sum n: freeze(p,n).
transfer(o,r,n) :- transferFrom(o,r,_,n).
invalidTx() :- recv_mint(_,_),owner(o),msgSender(s),o!=s.
unfreeze(p,n) :- recv_unfreeze(p,n),n>=0.
freezeSum(s) :- s = sum n: freezeOf(_,n).
totalBalances(s) :- s = sum n: balanceOf(_,n).
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),n := m-l.