Interfaces:
allowance(address,address): int
balanceOf(address): int
recv_transferFrom(address,address,address,int)
recv_mint(address,int)
recv_increaseAllowance(address,address,int)
recv_transfer(address,address,int)
totalSupply(): int
recv_burn(address,int)
Indices:
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalUnfreeze,List(address, int),List(p, n)) -> List(0)
SimpleRelation(freezeOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(totalFreeze,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
Rules:
allMint(s) :- s = sum n: mint(_,n).
freezeOf(p,n) :- totalFreeze(p,f),totalUnfreeze(p,u),n := f-u.
balanceOf(p,s) :- s := (((n+i)-m)-o)-f,totalBurn(p,m),freezeOf(p,f),totalMint(p,n),totalOut(p,o),totalIn(p,i).
unfreeze(p,n) :- recv_unfreeze(p,n).
transfer(o,r,n) :- transferFrom(o,r,_,n).
allowanceTotal(o,s,m) :- increaseAllowance(o,s,_),m = sum n: increaseAllowance(o,s,n).
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),n := m-l.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
burn(p,n) :- recv_burn(p,n),balanceOf(p,balanceOf_x1),n<=balanceOf_x1.
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
totalUnfreeze(p,s) :- unfreeze(p,_),s = sum n: unfreeze(p,n).
owner(s) :- constructor(_),msgSender(s).
freeze(p,n) :- recv_freeze(p,n).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
withdrawEther(p,n) :- recv_withdrawEther(p,n).
totalFreeze(p,s) :- freeze(p,_),s = sum n: freeze(p,n).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),balanceOf(o,balanceOf_x1_1),n>0,n<balanceOf_x1_1.
mint(p,n) :- recv_mint(p,n),n>=0.
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).