Interfaces:
allowance(address,address): int
raised(): int
recv_mint(address,int)
recv_increaseAllowance(address,address,int)
finalized(): bool
recv_transfer(address,address,int)
recv_finalize()
totalSupply(): int
recv_burn(address,int)
balanceOf(address): int
recv_buyToken(address,int)
cap(): int
recv_transferFrom(address,address,address,int)
Indices:
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeAllowance,List(address, address, int),List(s, p, n)) -> List(0, 1)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
Rules:
allMint(s) :- s = sum n: mint(_,n).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
mint(p,n) :- buyToken(p,m),rate(r),n := m*r.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
invalidTx() :- recv_burn(_,_),owner(o),msgSender(s),o!=s.
totalSupply(0) :- constructor(_,_).
onceFinalize(true) :- finalize().
finalized(true) :- finalize().
balanceOf(p,s) :- totalBurn(p,m),s := ((n+i)-m)-o,totalMint(p,n),totalOut(p,o),totalIn(p,i).
onceFinalize(false) :- constructor(_,_).
cap(c) :- constructor(c,_),c>0.
allowanceTotal(o,s,m) :- increaseAllowance(o,s,_),m = sum n: increaseAllowance(o,s,n).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).
buyToken(p,m) :- recv_buyToken(p,m),m>0.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>=0,n<=balanceOf_x1_1.
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
owner(s) :- constructor(_,_),msgSender(s).
negativeAllowance(s,p,n) :- allowance(s,p,n),n<0,s!=address(0),p!=address(0).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
finalize() :- recv_finalize(),raised(raised_n),raised_n<0.
transferFrom(o,r,s,n) :- n>0,allowance(o,s,allowance_x2_1),balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<=allowance_x2_1,n<balanceOf_x1_2.
rate(r) :- constructor(_,r),r>0.
illegalFinalization() :- onceFinalize(true),raised(r),cap(c),r<c.
invalidTx() :- recv_mint(_,_),owner(o),msgSender(s),o!=s.
transfer(o,r,n) :- transferFrom(o,r,_,n).
buyAfterFinalize() :- recv_buyToken(_,_),onceFinalize(true).
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),n := m-l.
raised(s) :- s = sum n: buyToken(_,n).