Interfaces:
allowance(address,address): int
balanceOf(address): int
recv_controllerRedeem(address,int)
owner(): address
recv_transferFrom(address,address,address,int)
recv_mint(address,int)
recv_increaseAllowance(address,address,int)
controller(): address
recv_transfer(address,address,int)
totalSupply(): int
recv_burn(address,int)
Indices:
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(illegalRedeem,List(address, int),List(p, n)) -> List(0)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
Rules:
allMint(s) :- s = sum n: mint(_,n).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
totalBalances(0) :- constructor(_).
balanceOf(p,s) :- totalBurn(p,m),s := ((n+i)-m)-o,totalMint(p,n),totalOut(p,o),totalIn(p,i).
transfer(o,r,n) :- transferFrom(o,r,_,n).
owner(s) :- constructor(_),msgSender(s).
allowanceTotal(o,s,m) :- increaseAllowance(o,s,_),m = sum n: increaseAllowance(o,s,n).
burn(p,n) :- recv_burn(p,n),balanceOf(p,balanceOf_x1),n<=balanceOf_x1.
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalSupply(0) :- constructor(_).
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
controllerRedeem(p,n) :- controller(controller_p_0),n<=balanceOf_x1_1,p==controller_p_0,balanceOf(p,balanceOf_x1_1),recv_controllerRedeem(p,n).
illegalRedeem(p,n) :- recv_controllerRedeem(p,n),controller(c),p!=c.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),balanceOf(o,balanceOf_x1_1),n>=0,n<balanceOf_x1_1.
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
controller(p) :- constructor(p).
transfer(s,r,n) :- controllerTransfer(s,r,n).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d).
totalBalances(s) :- s = sum n: balanceOf(_,n).
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),n := m-l.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>=0,n<balanceOf_x1_1.
unequalBalance(s,n) :- totalBalances(s),totalSupply(n),s!=n.
mint(p,n) :- recv_mint(p,n),n>=0.
burn(p,n) :- controllerRedeem(p,n).
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).
controllerTransfer(s,r,n) :- recv_controllerTransfer(s,r,n).