increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
burn(p,n) :- o_1==s_1,n>0,n<=m_2,p!=address(0),msgSender(s_1),balanceOf(p,m_2),owner(o_1),recv_burn(p,n).
transfer(s,r,n) :- s!=address(0),r!=address(0),n<=m_1,balanceOf(s,m_1),recv_transfer(s,r,n),n>0.
mint(p,n) :- o_1==s_1,n>0,p!=address(0),recv_mint(p,n),msgSender(s_1),owner(o_1).
controllerTransfer(s,r,n) :- s_1==c_1,n>0,n<=m_2,s!=address(0),r!=address(0),msgSender(s_1),controller(c_1),balanceOf(s,m_2),recv_controllerTransfer(s,r,n).
controllerRedeem(p,n) :- s_1==c_1,n>0,n<=m_2,p!=address(0),controller(c_1),balanceOf(p,m_2),msgSender(s_1),recv_controllerRedeem(p,n).
transferFrom(o,r,s,n) :- n>0,s!=address(0),r!=address(0),balanceOf(o,m_1),n<=m_1,recv_transferFrom(o,r,s,n),o!=address(0).