controllerRedeem(p,n) :- msgSender(s),s==c,n<=balanceOf_x1,controller(c),balanceOf(p,balanceOf_x1),recv_controllerRedeem(p,n).
controllerTransfer(s,r,n) :- msgSender(s),s==c,controller(c),controller(controller_p),recv_controllerTransfer(s,r,n),r==controller_p.
transferFrom(o,r,s,n) :- n>0,allowance(o,s,allowance_x2_1),n<allowance_x2_1,balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<balanceOf_x1_2.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
mint(p,n) :- recv_mint(p,n),n>0.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
burn(p,n) :- recv_burn(p,n),balanceOf(p,balanceOf_x1),n<=balanceOf_x1.