rely(p) :- recv_rely(p),owner(o),msgSender(s),o==s.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),allowance(o,s,allowance_x2),n<allowance_x2.
mint(p,n) :- msgSender(s),n>0,recv_mint(p,n),ward(w),w==s.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),recv_burn(p,n),ward(w),w==s.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.