transferFrom(t,o,r,sp,n) :- recv_transferFrom(t,o,r,sp,n),allowance(t,sp,msgSender,allowance_x3),msgSender(msgSender),n<allowance_x3.
increaseAllowance(t,o,s,d) :- recv_increaseAllowance(t,o,s,d),d>0.
mint(t,p,n) :- msgSender(s),n>0,o==s,owner(o),recv_mint(t,p,n).
transfer(t,s,r,n) :- recv_transfer(t,s,r,n),balanceOf(t,s,balanceOf_x2_1),n>0,n<=balanceOf_x2_1.
burn(t,p,n) :- msgSender(s),balanceOf(t,p,balanceOf_x2),n==balanceOf_x2,o==s,recv_burn(t,p,n),owner(o).