transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),allowance(o,s,allowance_x2),n<allowance_x2.
setMinter(p) :- recv_setMinter(p),owner(o),msgSender(s),o==s.
mint(p,n) :- msgSender(s),minter(m),recv_mint(p,n),n>=0,m==s.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>=0,n<=balanceOf_x1_1.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).