increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),allowance(o,s,allowance_x2),n<allowance_x2.
burnFrom(from,s,n) :- n<=allowance_x2_0,msgSender(s_p_1),s==s_p_1,allowance(msgSender,from,allowance_x2_1),0==allowance_x2_1,allowance(s,from,allowance_x2_0),n>0,msgSender(msgSender),recv_burnFrom(from,s,n).
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),p==s,recv_burn(p,n).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.