mint(p,n) :- cap(c_1),o_0==s_0,msgSender(s_0),recv_mint(p,n),owner(o_0),totalSupply(s_1),n+s_1<=c_1,n>=0.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),cap(cap_n),n>0,0!=cap_n.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
transfer(s,r,n) :- recv_transfer(s,r,n),allowance(r,s,allowance_x2),n>0,0!=allowance_x2.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).