buyToken(p,n) :- now(t_0),t_1<=e_1,end(e_1),recv_buyToken(p,m),start(s_0),now(t_1),t_0>=s_0.
transferFrom(o,r,s,n) :- allowance(o,s,allowance_x2_1),n<allowance_x2_1,balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n>=0,n<=balanceOf_x1_2.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>=0,n<=balanceOf_x1_1.
finalize() :- end(e_1),owner(o_0),o_0==s_0,now(t_1),recv_finalize(),msgSender(s_0),t_1>=e_1.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
mint(p,n) :- msgSender(s),n>0,recv_mint(p,n),o==s,owner(o).