finalize() :- msgSender(s),0!=end_time,o==s,owner(o),end(end_time),recv_finalize().
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
buyToken(p,m) :- recv_buyToken(p,m).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
transferFrom(o,r,s,n) :- n>0,allowance(o,s,allowance_x2_1),n<allowance_x2_1,balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<=balanceOf_x1_2.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
mint(p,n) :- msgSender(s),n>0,recv_mint(p,n),o==s,owner(o).