// SPDX-License-Identifier: MIT
pragma solidity ^0.8.21;

interface IERC20 {
    function balanceOf(address account) external view returns (uint256);
}

/**
 * UDF base contract for the `jokintheboxstakin` benchmark.
 *
 * NOTE:
 * - The synthesis pipeline will compose this file into the generated contract.
 * - Keep function signatures aligned with `.udf` relations in `schema.dl`.
 * - NonceTuple matches the struct generated by the synthesizer for
 *   `.decl nonce(sender: address, n: uint)[0]`, ensuring no type conflict.
 */
contract JokintheboxstakinUDF {
    // NonceTuple mirrors the synthesizer-generated struct for the `nonce` relation.
    // This avoids the uint256 vs. NonceTuple type conflict in the composed contract.
    struct NonceTuple { uint n; bool _valid; }

    IERC20 public jokToken = IERC20(0xA728Aa2De568766E2Fa4544Ec7A77f79c0bf9F97);
    address public stakingSigner = 0x8aaBaf348B299E759D091F17100a95A0F9caD89C;
    mapping(address => NonceTuple) nonce;

    // isValidSignature(sender, totalEarnings, inETH, messageHash, v, r, s, valid)
    // Reads nonce[beneficiary].n to match the NonceTuple mapping layout.
    function isValidSignature(
        address beneficiary,
        uint256 amount,
        bool inETH,
        bytes32 messageHash,
        uint256 v,
        bytes32 r,
        bytes32 s
    ) internal view returns (bool) {
        bytes32 payloadHash = keccak256(
            abi.encodePacked(address(this), beneficiary, amount, inETH, messageHash, nonce[beneficiary].n)
        );
        bytes32 prefixedHash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", payloadHash));
        address recoveredSigner = ecrecover(prefixedHash, uint8(v), r, s);
        return recoveredSigner == stakingSigner;
    }

    // jokTokenBalance() — state-reading UDF: returns JOK token balance held by this contract.
    function jokTokenBalance() internal view returns (uint256) {
        return jokToken.balanceOf(address(this));
    }

    // isValidLockPeriod(lockPeriod) — pure UDF: returns true for the four valid lock durations.
    // Original contract constructor initialises: 1, 30, 60, 90 days.
    function isValidLockPeriod(uint256 lockPeriod) external pure returns (bool) {
        return lockPeriod == 1 || lockPeriod == 30 ||
               lockPeriod == 60 || lockPeriod == 90;
    }

    function _setStakingSigner(address _stakingSigner) internal {
        stakingSigner = _stakingSigner;
    }

    function _setJokToken(address _jokToken) internal {
        jokToken = IERC20(_jokToken);
    }
}
