mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
decreaseApproval(o,s,n) :- recv_decreaseApproval(o,s,n),allowance(o,s,allowance_x2),n<allowance_x2.
transfer(s,r,n) :- 0!=allowance_x2_1,n<allowance_x2_2,msgSender(msgSender),allowance(msgSender,r,allowance_x2_1),n>=0,allowance(r,s,allowance_x2_2),r!=t_1,this(t_1),recv_transfer(s,r,n),allowance(s,msgSender,allowance_x2_3),n<=allowance_x2_3,r!=address(0).
increaseApproval(o,s,n) :- recv_increaseApproval(o,s,n),n>0.
transferFrom(o,r,s,n) :- allowance_x2_2>0,allowance(o,s,allowance_x2_1),0!=allowance_x2_0,allowance(r,o,allowance_x2_2),recv_transferFrom(o,r,s,n),n<=allowance_x2_1,allowance(s,r,allowance_x2_0).
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).