decreaseApproval(o,s,n) :- recv_decreaseApproval(o,s,n),balanceOf(s,balanceOf_x1),n<balanceOf_x1.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),owner(o),s==o,recv_burn(p,n).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1),0!=balanceOf_x1.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),allowance(o,s,allowance_x2),n<=allowance_x2.
increaseApproval(o,s,n) :- recv_increaseApproval(o,s,n),n>0.
mint(p,n) :- msgSender(s),n>0,recv_mint(p,n),owner(o),s==o.