mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
burn(p,n) :- msgSender(s),n<balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
swapOwnerTx(p,q,d) :- recv_swapOwnerTx(p,q,d),owner(o),msgSender(s),o==s.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<balanceOf_x1_1.
transferFrom(o,r,s,n) :- allowance(o,s,allowance_x2_1),n<allowance_x2_1,balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n>=0,n<=balanceOf_x1_2.