mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
burn(p,n) :- msgSender(s),balanceOf(p,balanceOf_x1),o==s,balanceOf_x1>0,owner(o),recv_burn(p,n).
increaseAllowance(o,s,n) :- recv_increaseAllowance(o,s,n),n>0.
pause() :- recv_pause().
transferFrom(o,r,s,n) :- 0!=balanceOf_x1,paused(b),b!=true,recv_transferFrom(o,r,s,n),balanceOf(r,balanceOf_x1).
decreaseAllowance(o,s,n) :- recv_decreaseAllowance(o,s,n),balanceOf(o,balanceOf_x1),balanceOf_x1>0.
transfer(s,r,n) :- recv_transfer(s,r,n),paused(b),b!=true.
unpause() :- recv_unpause().