Interfaces:
recv_burnFrom(address,address,int)
allowance(address,address): int
balanceOf(address): int
recv_transfer(address,address,int)
recv_increaseAllowance(address,address,int)
totalSupply(): int
recv_burn(address,int)
recv_mint(address,int)
recv_transferFrom(address,address,address,int)
Indices:
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeAllowance,List(address, address, int),List(s, p, n)) -> List(0, 1)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
Rules:
allMint(s) :- s = sum n: mint(_,n).
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
totalSupply(0) :- constructor().
burn(p,n) :- burnFrom(_,p,n).
invalidTx() :- recv_mint(_,_),owner(o),msgSender(s),o!=s.
transferFrom(s,p,address(0),n) :- burnFrom(s,p,n).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<balanceOf_x1_1.
transferFrom(o,r,s,n) :- allowance(o,s,allowance_x2_1),balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<=balanceOf_x1_2,n<=allowance_x2_1,n>=0.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
negativeAllowance(s,p,n) :- allowance(s,p,n),n<0,s!=address(0),p!=address(0).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
invalidTx() :- recv_burn(_,_),owner(o),msgSender(s),o!=s.
burnFrom(s,p,n) :- recv_burnFrom(s,p,n),balanceOf(s,balanceOf_x1),n<=balanceOf_x1.
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
transfer(o,r,n) :- transferFrom(o,r,_,n).
balanceOf(p,s) :- totalBurn(p,m),s := ((n+i)-m)-o,totalMint(p,n),totalOut(p,o),totalIn(p,i).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
owner(s) :- constructor(),msgSender(s).
allowanceTotal(o,s,m) :- increaseAllowance(o,s,_),m = sum n: increaseAllowance(o,s,n).
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),n := m-l.
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).