transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),allowance(msgSender,o,allowance_x2),msgSender(msgSender),allowance_x2>0.
transfer(s,r,n) :- recv_transfer(s,r,n),allowance(msgSender,r,allowance_x2),msgSender(msgSender),0!=allowance_x2.
burnFrom(s,p,n) :- recv_burnFrom(s,p,n),allowance(msgSender,p,allowance_x2),msgSender(msgSender),0!=allowance_x2.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
burn(p,n) :- msgSender(s),o==s,owner(o),0!=allowance_x2,recv_burn(p,n),msgSender(msgSender),allowance(msgSender,p,allowance_x2).