transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),balanceOf(o,m_1),n>0,n<=m_1.
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d).
burn(p,n) :- o_1==s_1,n>0,msgSender(s_1),owner(o_1),recv_burn(p,n).
burnFrom(s,p,n) :- recv_burnFrom(s,p,n),n>0.
transfer(s,r,n) :- s!=address(0),r!=address(0),n<=m_1,balanceOf(s,m_1),recv_transfer(s,r,n),n>0.