// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

// UDF implementations for the STBT (ERC1400-style) token benchmark.
//
// canSend / canRecv encapsulate the permission gate with expiry:
//   - allowed flag must be true
//   - either expiry == 0 (no expiry) OR current time is before expiry
//
// State variables referenced here are generated by the synthesizer from
// the Datalog schema:
//   permissionSendAllowed    -> mapping(address => PermissionSendAllowedTuple)    (field: .b)
//   permissionReceiveAllowed -> mapping(address => PermissionReceiveAllowedTuple) (field: .b)
//   permissionExpiryTime     -> mapping(address => PermissionExpiryTimeTuple)     (field: .t)

contract StbtUDF {
    struct PermissionSendAllowedTuple { bool b; bool _valid; }
    struct PermissionReceiveAllowedTuple { bool b; bool _valid; }
    struct PermissionExpiryTimeTuple { uint t; bool _valid; }

    mapping(address => PermissionSendAllowedTuple) permissionSendAllowed;
    mapping(address => PermissionReceiveAllowedTuple) permissionReceiveAllowed;
    mapping(address => PermissionExpiryTimeTuple) permissionExpiryTime;

    function canSend(address addr) external view returns (bool) {
        if (!permissionSendAllowed[addr].b) return false;
        uint expire = permissionExpiryTime[addr].t;
        return expire == 0 || block.timestamp < expire;
    }

    function canRecv(address addr) external view returns (bool) {
        if (!permissionReceiveAllowed[addr].b) return false;
        uint expire = permissionExpiryTime[addr].t;
        return expire == 0 || block.timestamp < expire;
    }
}
