transferFrom(o,r,sp,n) :- n>0,recv_transferFrom(o,r,sp,n),balanceOf(o,balanceOf_x1_2),n<=allowance_x2_1,allowance(o,sp,allowance_x2_1),n<balanceOf_x1_2.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),owner(o),s==o,recv_burn(p,n).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
distributeInterests(n,t) :- recv_distributeInterests(n,t),permissionExpiryTime(msgSender,permissionExpiryTime_x1),msgSender(msgSender),permissionExpiryTime_x1>0.
mint(p,n) :- msgSender(s),n>0,recv_mint(p,n),owner(o),s==o.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.