addBlackList(p) :- recv_addBlackList(p),owner(o),msgSender(s),o==s.
destroyBlackFund(p,n) :- msgSender(s),recv_destroyBlackFund(p,n),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),owner(o),s==o.
transfer(s,r,n) :- recv_transfer(s,r,n),isBlackListed(s,isBlackListed_x1),isBlackListed_x1==false.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
issue(p,n) :- msgSender(s),n>0,recv_issue(p,n),owner(o),s==o.
redeem(p,n) :- msgSender(s),recv_redeem(p,n),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),owner(o),s==o.
transferFrom(o,r,s,n) :- n>0,isBlackListed(msgSender,isBlackListed_x1_3),msgSender(msgSender),recv_transferFrom(o,r,s,n),n<=balanceOf_x1_2,n<allowance_x2_1,isBlackListed_x1_3==false,allowance(s,r,allowance_x2_1),balanceOf(o,balanceOf_x1_2).