addBlackList(p) :- recv_addBlackList(p),owner(o),msgSender(s),o==s.
transfer(s,r,n) :- fee_2<n,s!=address(0),computeFee(n,fee_2),n<=balanceOf_x1,r!=address(0),balanceOf(s,balanceOf_x1),n<=m_1,balanceOf(s,m_1),recv_transfer(s,r,n),n>0.
transferFrom(o,r,s,n) :- recv_transferFrom(o,r,s,n),balanceOf(o,m_1),n>0,n<=m_1.
redeem(p,n) :- recv_redeem(p,n),balanceOf(p,balanceOf_x1),0!=balanceOf_x1.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
issue(p,n) :- msgSender(s),n>0,recv_issue(p,n),o==s,owner(o).
destroyBlackFund(p,n) :- msgSender(s),recv_destroyBlackFund(p,n),balanceOf(p,balanceOf_x1),o==s,balanceOf_x1>0,owner(o).