transferFrom(o,r,sp,n) :- n>0,recv_transferFrom(o,r,sp,n),balanceOf(o,balanceOf_x1_2),n<=allowance_x2_1,allowance(o,sp,allowance_x2_1),n<balanceOf_x1_2.
disallowPrecirculation(p) :- recv_disallowPrecirculation(p),owner(o),msgSender(s),s==o.
allowPrecirculation(p) :- recv_allowPrecirculation(p),owner(o),msgSender(s),s==o.
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>0.
mint(p,n) :- recv_mint(p,n),n>0.
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<=balanceOf_x1_1.
burn(p,n) :- recv_burn(p,n),balanceOf(p,balanceOf_x1),n<=balanceOf_x1.