transfer(s,r,n) :- s!=address(0),r!=address(0),n<=m_1,recv_transfer(s,r,n),canTransfer(s,r,ok_2),n>0,ok_2!=false,balanceOf(s,m_1).
increaseAllowance(o,s,d) :- recv_increaseAllowance(o,s,d),d>=0.
burn(p,n) :- o_1==s_1,n<=m_2,p!=address(0),msgSender(s_1),balanceOf(p,m_2),owner(o_1),recv_burn(p,n).
allowPrecirculation(p) :- recv_allowPrecirculation(p),owner(o),msgSender(s),o==s.
mint(p,n) :- o_1==s_1,p!=address(0),recv_mint(p,n),msgSender(s_1),owner(o_1).
transferFrom(o,r,sp,n) :- sp!=address(0),balanceOf(o,m_1),n<=m_1,o!=address(0),canTransfer(o,r,ok_0),n<=k_3,allowance(o,sp,k_3),r!=address(0),ok_0!=false,recv_transferFrom(o,r,sp,n).
disallowPrecirculation(p) :- recv_disallowPrecirculation(p),owner(o),msgSender(s),o==s.