Interfaces:
totalSupply(): int
balanceOfByPartition(address,int): int
totalSupplyByPartition(int): int
recv_issueByPartition(address,int,int)
recv_transferByPartition(address,address,int,int)
recv_redeemByPartition(address,int,int)
Indices:
SimpleRelation(totalOut,List(address, int, int),List(p, q, n)) -> List(0, 1)
SimpleRelation(redeemTotalByPartition,List(int, int),List(q, n)) -> List(0)
SimpleRelation(balanceOfByPartition,List(address, int, int),List(p, q, n)) -> List(0, 1)
SimpleRelation(negativeBalance,List(address, int, int),List(p, q, n)) -> List(0)
SimpleRelation(issueTotalByPartition,List(int, int),List(q, n)) -> List(0)
SimpleRelation(totalIn,List(address, int, int),List(p, q, n)) -> List(0, 1)
SimpleRelation(totalBurn,List(address, int, int),List(p, q, n)) -> List(0, 1)
SimpleRelation(totalSupplyByPartition,List(int, int),List(q, n)) -> List(0)
SimpleRelation(totalMint,List(address, int, int),List(p, q, n)) -> List(0, 1)
Rules:
redeemTotalByPartition(q,s) :- redeemByPartition(_,q,_),s = sum n: redeemByPartition(_,q,n).
totalSupplyByPartition(q,n) :- issueTotalByPartition(q,i),redeemTotalByPartition(q,r),n := i-r.
invalidTx() :- recv_redeemByPartition(_,_,_),owner(o),msgSender(s),o!=s.
totalSupply(0) :- constructor().
allBurn(s) :- s = sum n: redeemByPartition(_,_,n).
invalidTx() :- recv_issueByPartition(_,_,_),owner(o),msgSender(s),o!=s.
issueTotalByPartition(q,s) :- issueByPartition(_,q,_),s = sum n: issueByPartition(_,q,n).
totalIn(p,q,s) :- transferByPartition(_,p,q,_),s = sum n: transferByPartition(_,p,q,n).
owner(s) :- constructor(),msgSender(s).
negativeBalance(p,q,n) :- balanceOfByPartition(p,q,n),n<0,p!=address(0).
totalMint(p,q,s) :- issueByPartition(p,q,_),s = sum n: issueByPartition(p,q,n).
allMint(s) :- s = sum n: issueByPartition(_,_,n).
totalBurn(p,q,s) :- redeemByPartition(p,q,_),s = sum n: redeemByPartition(p,q,n).
balanceOfByPartition(p,q,s) :- totalBurn(p,q,m),totalMint(p,q,n),s := ((n+i)-m)-o,totalIn(p,q,i),totalOut(p,q,o).
transferByPartition(s,r,q,n) :- recv_transferByPartition(s,r,q,n),0==n.
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
issueByPartition(p,q,n) :- msgSender(s),n>0,recv_issueByPartition(p,q,n),o==s,owner(o).
redeemByPartition(p,q,n) :- msgSender(s),recv_redeemByPartition(p,q,n),o==s,owner(o),0==n.
totalOut(p,q,s) :- transferByPartition(p,_,q,_),s = sum n: transferByPartition(p,_,q,n).