Interfaces:
recv_claimOwnership(address)
allowance(address,address): int
recv_increaseApproval(address,address,int)
balanceOf(address): int
recv_decreaseApproval(address,address,int)
recv_transfer(address,address,int)
recv_unpause()
recv_pause()
totalSupply(): int
recv_burn(address,int)
recv_mint(address,int)
recv_transferOwnership(address)
recv_transferFrom(address,address,address,int)
Indices:
SimpleRelation(allowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(spentTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(allowance,List(address, address, int),List(p, s, n)) -> List(0, 1)
SimpleRelation(totalMint,List(address, int),List(p, n)) -> List(0)
SimpleRelation(decreaseAllowanceTotal,List(address, address, int),List(o, s, m)) -> List(0, 1)
SimpleRelation(balanceOf,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeBalance,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalOut,List(address, int),List(p, n)) -> List(0)
SimpleRelation(totalIn,List(address, int),List(p, n)) -> List(0)
SimpleRelation(negativeAllowance,List(address, address, int),List(s, p, n)) -> List(0, 1)
SimpleRelation(totalBurn,List(address, int),List(p, n)) -> List(0)
Rules:
allMint(s) :- s = sum n: mint(_,n).
negativeBalance(p,n) :- balanceOf(p,n),n<0,p!=address(0).
totalSupply(0) :- constructor().
transferFrom(o,r,s,n) :- n>0,allowance(o,s,allowance_x2_1),balanceOf(o,balanceOf_x1_2),recv_transferFrom(o,r,s,n),n<=allowance_x2_1,n<balanceOf_x1_2.
transferOwnership(p) :- o_1==s_1,p!=address(0),msgSender(s_1),owner(o_1),recv_transferOwnership(p).
totalIn(p,s) :- transfer(_,p,_),s = sum n: transfer(_,p,n).
invalidTx() :- recv_unpause(),paused(b),b==false.
invalidTx() :- recv_claimOwnership(p),p==address(0).
invalidTx() :- recv_pause(),paused(b),b==true.
increaseApproval(o,s,n) :- recv_increaseApproval(o,s,n),n>=0.
pendingOwner(address(0)) :- claimOwnership(_).
totalBurn(p,s) :- burn(p,_),s = sum n: burn(p,n).
claimOwnership(p) :- recv_claimOwnership(p),pendingOwner(s_1),p!=address(0),s_1!=p.
invalidTx() :- recv_unpause(),owner(o),msgSender(s),o!=s.
invalidTx() :- recv_transferOwnership(p),p==address(0).
mint(p,n) :- msgSender(s),recv_mint(p,n),o==s,owner(o),n>=0.
negativeAllowance(s,p,n) :- allowance(s,p,n),n<0,s!=address(0),p!=address(0).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m),allBurn(b),n := m-b.
spentTotal(o,s,m) :- transferFrom(o,_,s,_),m = sum n: transferFrom(o,_,s,n).
allowance(o,s,n) :- allowanceTotal(o,s,m),spentTotal(o,s,l),decreaseAllowanceTotal(o,s,d),n := (m-l)-d.
invalidTx() :- recv_burn(_,_),owner(o),msgSender(s),o!=s.
invalidTx() :- recv_pause(),owner(o),msgSender(s),o!=s.
invalidTx() :- recv_transferOwnership(_),owner(o),msgSender(s),o!=s.
decreaseAllowanceTotal(o,s,m) :- decreaseApproval(o,s,_),m = sum n: decreaseApproval(o,s,n).
transfer(o,r,n) :- transferFrom(o,r,_,n).
balanceOf(p,s) :- totalBurn(p,m),s := ((n+i)-m)-o,totalMint(p,n),totalOut(p,o),totalIn(p,i).
invalidTx() :- recv_mint(_,_),owner(o),msgSender(s),o!=s.
paused(false) :- o_1==s_1,msgSender(s_1),b_0!=false,owner(o_1),recv_unpause(),paused(b_0).
totalMint(p,s) :- mint(p,_),s = sum n: mint(p,n).
allowanceTotal(o,s,m) :- increaseApproval(o,s,_),m = sum n: increaseApproval(o,s,n).
invalidTx() :- recv_claimOwnership(p),pendingOwner(s),s==p.
owner(s) :- constructor(),msgSender(s).
decreaseApproval(o,s,n) :- recv_decreaseApproval(o,s,n),allowance(o,s,allowance_x2),n<allowance_x2.
burn(p,n) :- msgSender(s),n<=balanceOf_x1,balanceOf(p,balanceOf_x1),o==s,owner(o),recv_burn(p,n).
totalOut(p,s) :- transfer(p,_,_),s = sum n: transfer(p,_,n).
pendingOwner(p) :- transferOwnership(p).
owner(s) :- claimOwnership(s).
transfer(s,r,n) :- recv_transfer(s,r,n),balanceOf(s,balanceOf_x1_1),n>0,n<balanceOf_x1_1.
paused(true) :- o_1==s_1,recv_pause(),msgSender(s_1),b_0!=true,paused(b_0),owner(o_1).