////////////////////
// Initialization
////////////////////
owner(s) :- constructor(), msgSender(s).
cap(86206) :- constructor().
bucketAmount(0) :- constructor().

crowdsaleFinalized(false) :- constructor().
continuousSaleStarted(false) :- constructor().
totalSupply(0) :- constructor().
weiRaised_1(0) :- constructor().
weiRaised_2(0) :- constructor().

////////////////////
// Crowdsale buyTokens
////////////////////
weiRaised_1(s) :- buyTokens(_,_), s = sum v: buyTokens(_, v).

mint(p,a) :- buyTokens(p,a).
totalMint(p,n) :- mint(p,_), n = sum m: mint(p,m).
totalSupply(n) :- totalMint(_,_), n = sum m: totalMint(_,m).

crowdsaleFinalized(true) :- finalize().

////////////////////
// Begin continuous sale
////////////////////
// transfer ownership of MANAToken to continuousSale (legacy behavior)
.decl transferOwnership(p: address)
transferOwnership(p) :- beginContinuousSale(), p := 10.
owner(s) :- transferOwnership(s).

// start continuousSale (legacy issuance computation)
.decl start()
start() :- beginContinuousSale(), totalSupply(a), n := a*8/100*12/1, issuance(n).
continuousSaleStarted(true) :- start().

////////////////////
// continuousSale buyToken1
////////////////////
processPurchase(p,a) :- buyToken1(p,a).

weiRaised_2(n) :- processPurchase(_,_), n = sum m: processPurchase(_, m).
mint(p,a) :- processPurchase(p,a).

// bucketAmount update (legacy behavior: last purchase amount)
.decl bucketAmount_increase(a:int)
bucketAmount_increase(a) :- processPurchase(_,a).
bucketAmount(a) :- bucketAmount_increase(a).

