////////////////////
// Global variables
////////////////////
.decl *owner(p: address)
.decl *weiRaised_1(a: int)
.decl *weiRaised_2(a: int)
.decl *cap(a: int)
.decl *bucketAmount(a: int)
.decl *issuance(a: int)

.decl *crowdsaleFinalized(b: bool)
.decl *continuousSaleStarted(b: bool)

.decl *totalSupply(a: int)

////////////////////
// Constructor
////////////////////
.decl constructor()

////////////////////
// Transactions
////////////////////
.decl recv_buyTokens(p: address, v: int)
.decl buyTokens(p: address, v: int)
.public recv_buyTokens

.decl recv_finalize()
.decl finalize()
.public recv_finalize

.decl recv_beginContinuousSale()
.decl beginContinuousSale()
.public recv_beginContinuousSale

.decl recv_buyToken1(p: address, v: int)
.decl buyToken1(p: address, v: int)
.public recv_buyToken1

////////////////////
// Internal helpers
////////////////////
.decl processPurchase(p: address, v: int)
.decl mint(p: address, a: int)
.decl totalMint(p: address, a: int)[0]

////////////////////
// Properties (violations)
////////////////////
.decl *alwaysLessThanIssuance(b: bool)
.decl *moreThanCap(b: bool)
.violation moreThanCap

.decl invalidTx()
.violation invalidTx

////////////////////
// Transaction placeholder rules
////////////////////
buyTokens(p,v) :- recv_buyTokens(p,v).
finalize() :- recv_finalize().
beginContinuousSale() :- recv_beginContinuousSale().
buyToken1(p,v) :- recv_buyToken1(p,v).

