// Initialization
owner(s) :- constructor(), msgSender(s).
totalSupply(0) :- constructor().

////////////////////
// ERC20 core accounting
////////////////////
totalOut(p,s) :- transfer(p,_,_), s = sum n: transfer(p,_,n).
totalIn(p,s) :- transfer(_,p,_), s = sum n: transfer(_,p,n).
totalMint(p,s) :- mint(p,_), s = sum n: mint(p,n).
totalBurn(p,s) :- burn(p,_), s = sum n: burn(p,n).
balanceOf(p,s) :- totalMint(p,n), totalBurn(p,m), totalOut(p,o), totalIn(p,i), s:=n+i-m-o.

allMint(s) :- s = sum n: mint(_,n).
allBurn(s) :- s = sum n: burn(_,n).
totalSupply(n) :- allMint(m), allBurn(b), n := m - b.

////////////////////
// Allowance
////////////////////
transfer(o,r,n) :- transferFrom(o,r,_,n).

allowanceTotal(o,s,m) :-
    increaseAllowance(o,s,_),
    m = sum n: increaseAllowance(o,s,n).

spentTotal(o,s,m) :-
    transferFrom(o,_,s,_),
    m = sum n: transferFrom(o,_,s,n).

allowance(o,s,n) :-
    allowanceTotal(o,s,m),
    spentTotal(o,s,l),
    n := m-l.

////////////////////
// ERC777 operator logic
////////////////////
operators(p,o,true) :- approveOperator(p,o).
revokedDefaultOperator(o,p,false) :- approveOperator(p,o).

revokedDefaultOperator(p,o,true) :- revokeDefaultOperator(p,o).
operators(p,o,false) :- revokeDefaultOperator(p,o).

transfer(o,r,n) :- operatorSend(o,r,_,n,_,_).
burn(p,n) :- operatorBurn(p,_,n,_,_).

